#!/bin/bash

echo "🔑 SUNO COOKIE UPDATE INSTRUCTIONS"
echo "=================================="
echo ""
echo "Your current cookie appears to be expired. Here's how to get a fresh one:"
echo ""
echo "📋 STEP-BY-STEP GUIDE:"
echo ""
echo "1. 🌐 Open your browser and go to: https://app.suno.ai"
echo "   (Note: Use app.suno.ai, not suno.com)"
echo ""
echo "2. 🔐 Log in to your Suno account if you're not already logged in"
echo ""
echo "3. 🛠️  Open Developer Tools:"
echo "   - Press F12 on your keyboard"
echo "   - Or right-click on the page and select 'Inspect'"
echo ""
echo "4. 🌐 Go to the 'Network' tab in Developer Tools"
echo ""
echo "5. 🔄 Refresh the page:"
echo "   - Press F5 or click the refresh button"
echo "   - Or press Ctrl+R (Cmd+R on Mac)"
echo ""
echo "6. 🔍 Find the right network request:"
echo "   - Look for a request that contains '?__clerk_api_version' in the URL"
echo "   - It might be something like: 'https://clerk.suno.com/...'"
echo "   - Click on this request when you find it"
echo ""
echo "7. 📋 Copy the Cookie header:"
echo "   - In the request details, click on the 'Headers' tab"
echo "   - Scroll down to find the 'Cookie' header"
echo "   - Hover over it and copy the entire cookie value"
echo "   - It should be a very long string starting with something like 'singular_device_id='"
echo ""
echo "8. 🔄 Update the environment variable:"
echo "   - Replace the SUNO_COOKIE value in your environment with the new cookie"
echo "   - Restart your development server"
echo ""
echo "9. ✅ Test the API:"
echo "   curl -X GET \"http://localhost:3000/api/get_limit\""
echo ""
echo "💡 TIPS:"
echo "- Make sure you're using https://app.suno.ai (not suno.com)"
echo "- The cookie expires after a few hours, so you may need to repeat this process"
echo "- If you can't find the request, try refreshing a few times"
echo "- The cookie should be very long (around 2000 characters)"
echo ""
echo "🚀 Once you have the fresh cookie, the API should work!"
